language: julia
julia:
    - 1.3

dist: focal

codecov: true

sudo: required

# Install system dependencies, namely a very barebones ROS setup.
before_install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt-get update
  - sudo apt-get install -y python3-rosdep ros-noetic-ros-base ros-noetic-geometry2 ros-noetic-std-msgs ros-noetic-std-srvs ros-noetic-actionlib-tutorials
  - source /opt/ros/noetic/setup.bash
  - sudo rosdep init
  - rosdep update
  - sudo cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ~/julia/lib/julia/libstdc++.so.6

jobs:
  include:
    - stage: "Tests"
      julia: 1.3
      os: linux
      script:
        - julia --project -e 'using Pkg;
                    ENV["JULIA_CXX_RTTI"]=1;
                    Pkg.add("Cxx");
                    Pkg.build("Cxx");
                    Pkg.add("Documenter");
                    Pkg.add("Libdl");
                    using Cxx;
                    Pkg.instantiate();'
        - source /opt/ros/noetic/setup.bash && roscore &
        - JULIA_NUM_THREADS=8 julia --code-coverage test/runtests.jl
      after_success:
        - rm src/gen/!(__*)
        - julia -e 'using Pkg; cd(Pkg.dir("ROS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project -e 'using Pkg;
                    ENV["JULIA_CXX_RTTI"]=1;
                    Pkg.add("Cxx");
                    Pkg.build("Cxx");
                    Pkg.add("Documenter");
                    Pkg.add("Libdl");
                    using Cxx;
                    Pkg.instantiate();'
        - source /opt/ros/noetic/setup.bash && julia --project docs/make.jl
      after_success: skip
